name: Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/dianabeetarb/spring-docker-auth:latest .
          docker push ghcr.io/dianabeetarb/spring-docker-auth:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: springbootauth2025
          images: ghcr.io/dianabeetarb/spring-docker-auth:latest
